/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CrewRouteImport } from './routes/crew'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as HelpRouteImport } from './routes/help'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VxControlRouteImport } from './routes/vx-control'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as Error400RouteImport } from './routes/error/400'
import { Route as Error401RouteImport } from './routes/error/401'
import { Route as Error403RouteImport } from './routes/error/403'
import { Route as Error408RouteImport } from './routes/error/408'
import { Route as Error429RouteImport } from './routes/error/429'
import { Route as Error500RouteImport } from './routes/error/500'
import { Route as Error502RouteImport } from './routes/error/502'
import { Route as Error503RouteImport } from './routes/error/503'
import { Route as Error504RouteImport } from './routes/error/504'
import { Route as PSlugRouteImport } from './routes/p/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewRoute = CrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VxControlRoute = VxControlRouteImport.update({
  id: '/vx-control',
  path: '/vx-control',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Error400Route = Error400RouteImport.update({
  id: '/error/400',
  path: '/error/400',
  getParentRoute: () => rootRouteImport,
} as any)
const Error401Route = Error401RouteImport.update({
  id: '/error/401',
  path: '/error/401',
  getParentRoute: () => rootRouteImport,
} as any)
const Error403Route = Error403RouteImport.update({
  id: '/error/403',
  path: '/error/403',
  getParentRoute: () => rootRouteImport,
} as any)
const Error408Route = Error408RouteImport.update({
  id: '/error/408',
  path: '/error/408',
  getParentRoute: () => rootRouteImport,
} as any)
const Error429Route = Error429RouteImport.update({
  id: '/error/429',
  path: '/error/429',
  getParentRoute: () => rootRouteImport,
} as any)
const Error500Route = Error500RouteImport.update({
  id: '/error/500',
  path: '/error/500',
  getParentRoute: () => rootRouteImport,
} as any)
const Error502Route = Error502RouteImport.update({
  id: '/error/502',
  path: '/error/502',
  getParentRoute: () => rootRouteImport,
} as any)
const Error503Route = Error503RouteImport.update({
  id: '/error/503',
  path: '/error/503',
  getParentRoute: () => rootRouteImport,
} as any)
const Error504Route = Error504RouteImport.update({
  id: '/error/504',
  path: '/error/504',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/crew': typeof CrewRoute
  '/download': typeof DownloadRoute
  '/help': typeof HelpRoute
  '/maintenance': typeof MaintenanceRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/vx-control': typeof VxControlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/error/400': typeof Error400Route
  '/error/401': typeof Error401Route
  '/error/403': typeof Error403Route
  '/error/408': typeof Error408Route
  '/error/429': typeof Error429Route
  '/error/500': typeof Error500Route
  '/error/502': typeof Error502Route
  '/error/503': typeof Error503Route
  '/error/504': typeof Error504Route
  '/p/$slug': typeof PSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/crew': typeof CrewRoute
  '/download': typeof DownloadRoute
  '/help': typeof HelpRoute
  '/maintenance': typeof MaintenanceRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/vx-control': typeof VxControlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/error/400': typeof Error400Route
  '/error/401': typeof Error401Route
  '/error/403': typeof Error403Route
  '/error/408': typeof Error408Route
  '/error/429': typeof Error429Route
  '/error/500': typeof Error500Route
  '/error/502': typeof Error502Route
  '/error/503': typeof Error503Route
  '/error/504': typeof Error504Route
  '/p/$slug': typeof PSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/crew': typeof CrewRoute
  '/download': typeof DownloadRoute
  '/help': typeof HelpRoute
  '/maintenance': typeof MaintenanceRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/vx-control': typeof VxControlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/error/400': typeof Error400Route
  '/error/401': typeof Error401Route
  '/error/403': typeof Error403Route
  '/error/408': typeof Error408Route
  '/error/429': typeof Error429Route
  '/error/500': typeof Error500Route
  '/error/502': typeof Error502Route
  '/error/503': typeof Error503Route
  '/error/504': typeof Error504Route
  '/p/$slug': typeof PSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/changelog'
    | '/contact'
    | '/cookies'
    | '/crew'
    | '/download'
    | '/help'
    | '/maintenance'
    | '/offline'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/vx-control'
    | '/blog/$slug'
    | '/error/400'
    | '/error/401'
    | '/error/403'
    | '/error/408'
    | '/error/429'
    | '/error/500'
    | '/error/502'
    | '/error/503'
    | '/error/504'
    | '/p/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/changelog'
    | '/contact'
    | '/cookies'
    | '/crew'
    | '/download'
    | '/help'
    | '/maintenance'
    | '/offline'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/vx-control'
    | '/blog/$slug'
    | '/error/400'
    | '/error/401'
    | '/error/403'
    | '/error/408'
    | '/error/429'
    | '/error/500'
    | '/error/502'
    | '/error/503'
    | '/error/504'
    | '/p/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/changelog'
    | '/contact'
    | '/cookies'
    | '/crew'
    | '/download'
    | '/help'
    | '/maintenance'
    | '/offline'
    | '/privacy'
    | '/status'
    | '/terms'
    | '/vx-control'
    | '/blog/$slug'
    | '/error/400'
    | '/error/401'
    | '/error/403'
    | '/error/408'
    | '/error/429'
    | '/error/500'
    | '/error/502'
    | '/error/503'
    | '/error/504'
    | '/p/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  CrewRoute: typeof CrewRoute
  DownloadRoute: typeof DownloadRoute
  HelpRoute: typeof HelpRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OfflineRoute: typeof OfflineRoute
  PrivacyRoute: typeof PrivacyRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  VxControlRoute: typeof VxControlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  Error400Route: typeof Error400Route
  Error401Route: typeof Error401Route
  Error403Route: typeof Error403Route
  Error408Route: typeof Error408Route
  Error429Route: typeof Error429Route
  Error500Route: typeof Error500Route
  Error502Route: typeof Error502Route
  Error503Route: typeof Error503Route
  Error504Route: typeof Error504Route
  PSlugRoute: typeof PSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew': {
      id: '/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof CrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vx-control': {
      id: '/vx-control'
      path: '/vx-control'
      fullPath: '/vx-control'
      preLoaderRoute: typeof VxControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/400': {
      id: '/error/400'
      path: '/error/400'
      fullPath: '/error/400'
      preLoaderRoute: typeof Error400RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/401': {
      id: '/error/401'
      path: '/error/401'
      fullPath: '/error/401'
      preLoaderRoute: typeof Error401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/403': {
      id: '/error/403'
      path: '/error/403'
      fullPath: '/error/403'
      preLoaderRoute: typeof Error403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/408': {
      id: '/error/408'
      path: '/error/408'
      fullPath: '/error/408'
      preLoaderRoute: typeof Error408RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/429': {
      id: '/error/429'
      path: '/error/429'
      fullPath: '/error/429'
      preLoaderRoute: typeof Error429RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/500': {
      id: '/error/500'
      path: '/error/500'
      fullPath: '/error/500'
      preLoaderRoute: typeof Error500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/502': {
      id: '/error/502'
      path: '/error/502'
      fullPath: '/error/502'
      preLoaderRoute: typeof Error502RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/503': {
      id: '/error/503'
      path: '/error/503'
      fullPath: '/error/503'
      preLoaderRoute: typeof Error503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/504': {
      id: '/error/504'
      path: '/error/504'
      fullPath: '/error/504'
      preLoaderRoute: typeof Error504RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  CrewRoute: CrewRoute,
  DownloadRoute: DownloadRoute,
  HelpRoute: HelpRoute,
  MaintenanceRoute: MaintenanceRoute,
  OfflineRoute: OfflineRoute,
  PrivacyRoute: PrivacyRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  VxControlRoute: VxControlRoute,
  BlogSlugRoute: BlogSlugRoute,
  Error400Route: Error400Route,
  Error401Route: Error401Route,
  Error403Route: Error403Route,
  Error408Route: Error408Route,
  Error429Route: Error429Route,
  Error500Route: Error500Route,
  Error502Route: Error502Route,
  Error503Route: Error503Route,
  Error504Route: Error504Route,
  PSlugRoute: PSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
