// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-published-pages.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var supabase = () => createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_PUBLISHABLE_KEY,
  { auth: { persistSession: false, autoRefreshToken: false } }
);
var list_published_pages_default = defineTool({
  name: "list_published_pages",
  title: "List VeloRix pages",
  description: "List all published VeloRix custom pages (tournaments, announcements, policies) with slug, title and subtitle.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const { data, error } = await supabase().from("custom_pages").select("slug,title,subtitle,updated_at").eq("published", true).order("updated_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { pages: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-page.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
var supabase2 = () => createClient2(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_PUBLISHABLE_KEY,
  { auth: { persistSession: false, autoRefreshToken: false } }
);
var get_page_default = defineTool2({
  name: "get_page",
  title: "Get VeloRix page",
  description: "Fetch the full markdown content of a published VeloRix custom page by slug.",
  inputSchema: {
    slug: z.string().min(1).describe("Page slug, e.g. 'diwali-cup' or 'refund-policy'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const { data, error } = await supabase2().from("custom_pages").select("slug,title,subtitle,content,updated_at").eq("published", true).eq("slug", slug.toLowerCase()).maybeSingle();
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No published page found for slug '${slug}'.` }], isError: true };
    return {
      content: [{ type: "text", text: `# ${data.title}

${data.subtitle ?? ""}

${data.content}` }],
      structuredContent: { page: data }
    };
  }
});

// src/lib/mcp/tools/get-active-apk.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var supabase3 = () => createClient3(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_PUBLISHABLE_KEY,
  { auth: { persistSession: false, autoRefreshToken: false } }
);
var get_active_apk_default = defineTool3({
  name: "get_active_apk",
  title: "Get active VeloRix APK",
  description: "Get the currently active VeloRix Android APK version, changelog, size and download path.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const { data, error } = await supabase3().from("apk_versions").select("version,file_path,file_size,changelog,released_at").eq("is_active", true).order("released_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No active APK version published yet." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { apk: data }
    };
  }
});

// src/lib/mcp/tools/get-site-status.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
var supabase4 = () => createClient4(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_PUBLISHABLE_KEY,
  { auth: { persistSession: false, autoRefreshToken: false } }
);
var get_site_status_default = defineTool4({
  name: "get_site_status",
  title: "Get VeloRix site status",
  description: "Check whether the VeloRix site is live or in maintenance mode, with the current status message.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const { data } = await supabase4().from("site_config").select("value").eq("key", "maintenance").maybeSingle();
    const cfg = data?.value ?? {};
    const enabled = Boolean(cfg.enabled);
    const status = enabled ? "maintenance" : "live";
    const message = cfg.message ?? "VeloRix is live.";
    return {
      content: [{ type: "text", text: `Status: ${status}
${message}` }],
      structuredContent: { status, maintenance: enabled, message }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "velorix-mcp",
  title: "VeloRix",
  version: "0.1.0",
  instructions: "Public tools for VeloRix \u2014 India's Free Fire / BGMI tournament platform. Use `list_published_pages` to discover tournaments, announcements and policy pages, `get_page` to read one, `get_active_apk` to get the current Android APK download info, and `get_site_status` to check if the site is live.",
  tools: [list_published_pages_default, get_page_default, get_active_apk_default, get_site_status_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
